lucklrj.lo: /www/start-zephir/lucklrj/ext/lucklrj.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/lucklrj.c -o lucklrj.lo 
kernel/main.lo: /www/start-zephir/lucklrj/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /www/start-zephir/lucklrj/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /www/start-zephir/lucklrj/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/exception.c -o kernel/exception.lo 
kernel/debug.lo: /www/start-zephir/lucklrj/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /www/start-zephir/lucklrj/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /www/start-zephir/lucklrj/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /www/start-zephir/lucklrj/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /www/start-zephir/lucklrj/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /www/start-zephir/lucklrj/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /www/start-zephir/lucklrj/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /www/start-zephir/lucklrj/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /www/start-zephir/lucklrj/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /www/start-zephir/lucklrj/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /www/start-zephir/lucklrj/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /www/start-zephir/lucklrj/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /www/start-zephir/lucklrj/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /www/start-zephir/lucklrj/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /www/start-zephir/lucklrj/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /www/start-zephir/lucklrj/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/kernel/exit.c -o kernel/exit.lo 
lucklrj/math/irr.lo: /www/start-zephir/lucklrj/ext/lucklrj/math/irr.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/lucklrj/math/irr.zep.c -o lucklrj/math/irr.lo 
lucklrj/test.lo: /www/start-zephir/lucklrj/ext/lucklrj/test.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/www/start-zephir/lucklrj/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /www/start-zephir/lucklrj/ext/lucklrj/test.zep.c -o lucklrj/test.lo 
$(phplibdir)/lucklrj.la: ./lucklrj.la
	$(LIBTOOL) --mode=install cp ./lucklrj.la $(phplibdir)

./lucklrj.la: $(shared_objects_lucklrj) $(LUCKLRJ_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_lucklrj) $(LUCKLRJ_SHARED_LIBADD)

